### PR TITLE
Use piptools

### PR DESCRIPTION
**Pull request by danparizher**
We can use `pip-tools` to use commands like `pip-sync` and `pip-compile`. Basically, we would have a new file called `requirements.in` which would house the packages we would normally have in `requirements.txt`. After compiling it, it will autogenerate all nested dependencies to `requirements.txt`, which `pip-sync` can then read and sync with your environment.

### CODE REVIEW

**Comment by sebastiaan-daniels** [comment]
I do not really see the use in this?
You can just pip install -r and you're ready to go?

**Comment by Arborym** [comment]
> I do not really see the use in this?
> You can just pip install -r and you're ready to go?

If a package is removed from the requirements file, it will not be removed from your venv. Piptools fixes that issue by syncing your venv exactly with what is needed in your environment

**Comment by sebastiaan-daniels** [comment]
> > I do not really see the use in this?
> > You can just pip install -r and you're ready to go?
> 
> If a package is removed from the requirements file, it will not be removed from your venv. Piptools fixes that issue by syncing your venv exactly with what is needed in your environment 

Do I _need_ to use this? Or can I just do it the normal way if I prefer to?

**Comment by Arborym** [comment]
No you don't have to, you can use `pip install -r requirements.txt` like you always have. It just helps with granularity. It shouldn't really affect anyone's workflow

**Review by sebastiaan-daniels — APPROVED** [review]

**Pull request merged**
